In [53]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from plotly.io import show
from datetime import datetime
from sklearn.model_selection import train_test_split

from skfolio import Population, RiskMeasure
from skfolio.datasets import load_sp500_dataset
from skfolio.optimization import (
    InverseVolatility,
    MeanRisk,
    ObjectiveFunction,
    EqualWeighted,
)
from skfolio.preprocessing import prices_to_returns

In [54]:
prices = load_sp500_dataset()
print(prices.columns)

Index(['AAPL', 'AMD', 'BAC', 'BBY', 'CVX', 'GE', 'HD', 'JNJ', 'JPM', 'KO',
       'LLY', 'MRK', 'MSFT', 'PEP', 'PFE', 'PG', 'RRC', 'UNH', 'WMT', 'XOM'],
      dtype='object')

In [67]:
cols = ['AAPL', 'AMD', 'BAC', 'GE', 'HD', 'JNJ', 'JPM', 'KO',
         'MSFT', 'PEP', 'PFE', 'PG', 'WMT', 'XOM']
prices = prices[cols]
X = prices_to_returns(prices)
X.head()

,AAPL,AMD,BAC,GE,HD,JNJ,JPM,KO,MSFT,PEP,PFE,PG,WMT,XOM
Date,,,,,,,,,,,,,,
1990-01-03,0.007576,-0.030303,0.008045,-0.001876,0.003581,0.004072,0.033589,-0.014318,0.005208,-0.009709,0.002938,-0.001813,0.000000,-0.010079
1990-01-04,0.003759,-0.015500,-0.021355,-0.005639,0.006244,0.002028,0.003991,-0.004993,0.028497,-0.009804,0.016602,-0.019725,-0.005201,-0.009933
1990-01-05,0.003745,-0.031996,-0.021821,-0.009452,-0.013298,-0.010408,0.003975,-0.008212,-0.025189,-0.013991,-0.008646,-0.018004,-0.010732,-0.005267
1990-01-08,0.003731,0.000000,0.005633,0.005725,-0.009883,0.016944,0.000000,0.021159,0.015504,0.018118,-0.008721,0.018334,0.013630,0.015381
1990-01-09,-0.007435,0.016527,0.000000,-0.020803,-0.026316,-0.031026,-0.031957,-0.007658,-0.002545,-0.013722,-0.021505,0.000000,-0.026619,-0.020114

In [56]:
X_month = (1 + X).resample('ME').prod() - 1
X_month.head()

,AAPL,AMD,BAC,GE,HD,JNJ,JPM,KO,MSFT,PEP,PFE,PG,WMT,XOM
Date,,,,,,,,,,,,,,
1990-01-31,-0.087121,-0.121212,-0.099369,-0.067403,-0.069830,-0.125364,-1.414260e-01,-0.117226,0.041667,-0.105108,-0.035260,-0.086528,-0.095538,-0.059980
1990-02-28,0.004149,0.137931,0.068083,-0.000447,0.132820,0.029265,-5.147563e-03,0.023822,0.067500,0.017453,-0.130964,-0.001985,0.032385,0.012552
1990-03-31,0.181818,0.105939,-0.129069,0.040477,0.151232,0.046527,-6.450500e-02,0.066337,0.121780,0.075104,0.026869,0.060813,0.075344,-0.015754
1990-04-30,-0.020979,-0.040991,-0.019465,-0.003940,0.021402,0.008953,4.440892e-16,0.019963,0.045929,0.057999,-0.063709,0.049022,0.050436,-0.021779
1990-05-31,0.050000,0.200000,0.029116,0.083507,0.296965,0.134333,1.710914e-01,0.183432,0.259481,0.115142,0.172539,0.169816,0.135998,0.074571

In [57]:
X_train, X_test = train_test_split(X_month, test_size=0.3, shuffle=False)
X_train.head()

,AAPL,AMD,BAC,GE,HD,JNJ,JPM,KO,MSFT,PEP,PFE,PG,WMT,XOM
Date,,,,,,,,,,,,,,
1990-01-31,-0.087121,-0.121212,-0.099369,-0.067403,-0.069830,-0.125364,-1.414260e-01,-0.117226,0.041667,-0.105108,-0.035260,-0.086528,-0.095538,-0.059980
1990-02-28,0.004149,0.137931,0.068083,-0.000447,0.132820,0.029265,-5.147563e-03,0.023822,0.067500,0.017453,-0.130964,-0.001985,0.032385,0.012552
1990-03-31,0.181818,0.105939,-0.129069,0.040477,0.151232,0.046527,-6.450500e-02,0.066337,0.121780,0.075104,0.026869,0.060813,0.075344,-0.015754
1990-04-30,-0.020979,-0.040991,-0.019465,-0.003940,0.021402,0.008953,4.440892e-16,0.019963,0.045929,0.057999,-0.063709,0.049022,0.050436,-0.021779
1990-05-31,0.050000,0.200000,0.029116,0.083507,0.296965,0.134333,1.710914e-01,0.183432,0.259481,0.115142,0.172539,0.169816,0.135998,0.074571

In [58]:
# use skfolio to implement MVO strategy
# use max sharpe ratio as the objective function
# for mean just use simlpe mean estimator, with alternative as stein shrinkage estimator
# for cov mat use ledoit wolf shrinkage estimator

from skfolio.prior import EmpiricalPrior
from skfolio.moments import EmpiricalMu, ShrunkMu, LedoitWolf, DenoiseCovariance

model = MeanRisk(
    risk_measure=RiskMeasure.STANDARD_DEVIATION,
    objective_function=ObjectiveFunction.MAXIMIZE_RATIO,
    prior_estimator=EmpiricalPrior(
        mu_estimator=EmpiricalMu(window_size=None),  # by default uses all given data
        covariance_estimator=LedoitWolf(),
    ),
    # note that default uses empirical prior -> ie empirical mu and cov
    portfolio_params=dict(name="Max Sharpe"),
)
model.fit(X_train)
model.weights_

array([8.50895718e-02, 8.20047462e-09, 1.04605259e-08, 1.82414725e-08,
       1.25791959e-01, 6.12311826e-02, 1.89180364e-08, 2.10776175e-02,
       7.55058813e-02, 2.46217573e-02, 6.35168251e-02, 1.88501435e-01,
       6.36043053e-02, 2.91059410e-01])

In [59]:
# model.prior_estimator_.mu_estimator_.window_size
# model.prior_estimator_.covariance_estimator_.shrinkage_

# model.prior_estimator_.return_distribution_
# model.prior_estimator_.return_distribution_.covariance

In [60]:
# compare against inverse vol and baseline 1/N allocation
# with rebalancing each period to make sure that
# the uniform allocation is up to date to the current prices

benchmark = InverseVolatility(portfolio_params=dict(name="Inverse Vol"))
benchmark.fit(X_train)
benchmark.weights_

array([0.03975662, 0.02779107, 0.0465962 , 0.07312476, 0.06636924,
       0.09299006, 0.05372087, 0.08762152, 0.05645132, 0.09075439,
       0.07751283, 0.09131714, 0.08110195, 0.11489202])

In [61]:
naive = EqualWeighted(portfolio_params=dict(name="Naive"))
naive.fit(X_train)
naive.weights_

array([0.07142857, 0.07142857, 0.07142857, 0.07142857, 0.07142857,
       0.07142857, 0.07142857, 0.07142857, 0.07142857, 0.07142857,
       0.07142857, 0.07142857, 0.07142857, 0.07142857])

In [62]:
pred_model = model.predict(X_test)
pred_bench = benchmark.predict(X_test)
pred_naive = naive.predict(X_test)

print(pred_model.annualized_sharpe_ratio)
print(pred_bench.annualized_sharpe_ratio)
print(pred_naive.annualized_sharpe_ratio)

4.692401848550191
4.665535777765448
4.984466269193997

In [63]:
# population = Population([pred_model, pred_bench, pred_naive])
population = Population([pred_model, pred_naive])
population.plot_composition()

In [64]:
fig = population.plot_cumulative_returns()
# show(fig) is only used for the documentation sticker.
show(fig)

In [65]:
population.summary()

                                           Max Sharpe     Naive
Mean                                            1.21%     1.39%
Annualized Mean                               303.67%   350.15%
Variance                                        0.17%     0.20%
Annualized Variance                            41.88%    49.35%
Semi-Variance                                  0.088%     0.10%
Annualized Semi-Variance                       22.26%    26.33%
Standard Deviation                              4.08%     4.43%
Annualized Standard Deviation                  64.72%    70.25%
Semi-Deviation                                  2.97%     3.23%
Annualized Semi-Deviation                      47.18%    51.31%
Mean Absolute Deviation                         2.89%     3.32%
CVaR at 95%                                     8.54%     8.60%
EVaR at 95%                                     9.61%     9.32%
Worst Realization                              11.15%    10.76%
CDaR at 95%                                    12.45%    14.79%
MAX Drawdown                                   23.01%    19.88%
Average Drawdown                                1.93%     2.56%
EDaR at 95%                                    18.09%    17.68%
First Lower Partial Moment                      1.44%     1.66%
Ulcer Index                                     0.040     0.048
Gini Mean Difference                            4.35%     4.93%
Value at Risk at 95%                            6.37%     6.32%
Drawdown at Risk at 95%                         9.70%     9.58%
Entropic Risk Measure at 95%                     2.98      2.98
Fourth Central Moment                         0.0013%   0.0012%
Fourth Lower Partial Moment                  0.00066%  0.00072%
Skew                                          -12.19%   -20.32%
Kurtosis                                      481.96%   328.06%
Sharpe Ratio                                     0.30      0.31
Annualized Sharpe Ratio                          4.69      4.98
Sortino Ratio                                    0.41      0.43
Annualized Sortino Ratio                         6.44      6.82
Mean Absolute Deviation Ratio                    0.42      0.42
First Lower Partial Moment Ratio                 0.83      0.84
Value at Risk Ratio at 95%                       0.19      0.22
CVaR Ratio at 95%                                0.14      0.16
Entropic Risk Measure Ratio at 95%             0.0040    0.0047
EVaR Ratio at 95%                                0.13      0.15
Worst Realization Ratio                          0.11      0.13
Drawdown at Risk Ratio at 95%                    0.12      0.15
CDaR Ratio at 95%                               0.097     0.094
Calmar Ratio                                    0.052     0.070
Average Drawdown Ratio                           0.62      0.54
EDaR Ratio at 95%                               0.067     0.079
Ulcer Index Ratio                                0.30      0.29
Gini Mean Difference Ratio                       0.28      0.28
Effective Number of Assets          6.176918924478376      14.0
Assets Number                                      14        14